print("What is the name of the gift giver")
name = input()
print("What is the present they gave you?")
present = input()
print("How old were you on your birthday?")
age = input()
print("What is your name")
yourname = input()
print("Dear "+ name + " ,")
print("")
print("Thank you for the "+ present + ". ")
print("I really like it. I can't believe ")
print("I am already "+ str(age) + "years old, but ")
print("It does not feel much different than being ")
print(str(int(age)-1)+ ". ")
print("")
print("Sincerely ")
print("")
print(yourname)
